# Generated by Django 4.2.2 on 2023-06-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_boob_first', models.BooleanField(default=False)),
                ('right_boob_time', models.IntegerField(default=0)),
                ('left_boob_first', models.BooleanField(default=False)),
                ('left_boob_time', models.IntegerField(default=0)),
                ('feed_time', models.DateTimeField(verbose_name='feed time')),
                ('notes', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Toileting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pee', models.BooleanField(default=False)),
                ('pee_scale', models.IntegerField(default=0)),
                ('poo', models.BooleanField(default=False)),
                ('poo_scale', models.IntegerField(default=0)),
                ('toilet_time', models.DateTimeField(verbose_name='toilet time')),
                ('notes', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
