# Generated by Django 4.2.2 on 2023-07-16 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_records', '0003_alter_toileting_pee_scale_alter_toileting_poo_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='left_boob_time',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='notes',
            field=models.CharField(default='n/a', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='right_boob_time',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='toileting',
            name='notes',
            field=models.CharField(default='n/a', max_length=200, null=True),
        ),
    ]
