# Generated by Django 4.2.2 on 2023-07-17 10:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_records', '0004_alter_feeding_left_boob_time_alter_feeding_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Growth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_circumference', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('height', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('measurement_time', models.DateTimeField(default=datetime.datetime(2023, 7, 17, 10, 46, 1, 571234, tzinfo=datetime.timezone.utc), verbose_name='growth measure time')),
                ('notes', models.CharField(default='n/a', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sleeping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nap_length', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('nap_start_time', models.DateTimeField(default=datetime.datetime(2023, 7, 17, 10, 46, 1, 571234, tzinfo=datetime.timezone.utc), verbose_name='nap start time')),
                ('nap_location', models.CharField(default='bedroom', max_length=200, null=True)),
                ('notes', models.CharField(default='n/a', max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feeding',
            name='feed_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 10, 46, 1, 571234, tzinfo=datetime.timezone.utc), verbose_name='feed time'),
        ),
        migrations.AlterField(
            model_name='toileting',
            name='toilet_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 10, 46, 1, 461456, tzinfo=datetime.timezone.utc), verbose_name='toilet time'),
        ),
    ]
