# Generated by Django 4.2.2 on 2023-07-17 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_records', '0006_sleeping_nap_quality_alter_feeding_feed_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='feed_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 10, 50, 46, 26381, tzinfo=datetime.timezone.utc), verbose_name='feed time'),
        ),
        migrations.AlterField(
            model_name='growth',
            name='measurement_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 10, 50, 46, 26381, tzinfo=datetime.timezone.utc), verbose_name='growth measure time'),
        ),
        migrations.AlterField(
            model_name='sleeping',
            name='nap_start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 10, 50, 46, 26381, tzinfo=datetime.timezone.utc), verbose_name='nap start time'),
        ),
        migrations.AlterField(
            model_name='toileting',
            name='toilet_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 10, 50, 45, 907093, tzinfo=datetime.timezone.utc), verbose_name='toilet time'),
        ),
    ]
