# Generated by Django 4.2.2 on 2023-07-25 04:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_records', '0009_alter_feeding_feed_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BottleFeeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinking_ml', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('drinking_time', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('feed_time', models.DateTimeField(default=datetime.datetime(2023, 7, 25, 4, 27, 57, 27174, tzinfo=datetime.timezone.utc), verbose_name='feed time')),
                ('notes', models.CharField(default='n/a', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BreastFeeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('which_boob_first', models.CharField(default='right')),
                ('right_boob_time', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('left_boob_time', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('feed_time', models.DateTimeField(default=datetime.datetime(2023, 7, 25, 4, 27, 57, 27174, tzinfo=datetime.timezone.utc), verbose_name='feed time')),
                ('notes', models.CharField(default='n/a', max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Feeding',
        ),
        migrations.AlterField(
            model_name='growth',
            name='measurement_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 4, 27, 57, 27174, tzinfo=datetime.timezone.utc), verbose_name='growth measure time'),
        ),
        migrations.AlterField(
            model_name='sleeping',
            name='nap_start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 4, 27, 57, 27174, tzinfo=datetime.timezone.utc), verbose_name='nap start time'),
        ),
        migrations.AlterField(
            model_name='toileting',
            name='toilet_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 4, 27, 56, 902306, tzinfo=datetime.timezone.utc), verbose_name='toilet time'),
        ),
    ]
