# Generated by Django 4.2.2 on 2023-07-26 07:14

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_records', '0010_bottlefeeding_breastfeeding_delete_feeding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottlefeeding',
            name='feed_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 7, 14, 11, 196762, tzinfo=datetime.timezone.utc), verbose_name='feed time'),
        ),
        migrations.AlterField(
            model_name='breastfeeding',
            name='feed_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 7, 14, 11, 196762, tzinfo=datetime.timezone.utc), verbose_name='feed time'),
        ),
        migrations.AlterField(
            model_name='growth',
            name='measurement_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 7, 14, 11, 196762, tzinfo=datetime.timezone.utc), verbose_name='growth measure time'),
        ),
        migrations.AlterField(
            model_name='growth',
            name='weight',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sleeping',
            name='nap_start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 7, 14, 11, 196762, tzinfo=datetime.timezone.utc), verbose_name='nap start time'),
        ),
        migrations.AlterField(
            model_name='toileting',
            name='toilet_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 7, 14, 11, 99621, tzinfo=datetime.timezone.utc), verbose_name='toilet time'),
        ),
    ]
